### ISSUE TITLE
Better GitHub Actions integration for Builds Reporting

### ISSUE THREAD

**Issue by yordis** [codecov/codecov-action#14]
Based on this setup https://codecov.io/gh/straw-hat-team/straw_hat_review/commit/61c7b08da9a38c89acbc6646c2a6e891b2011ea9/build

I would like to pass the build # and other metadata as Travis does today

For example https://codecov.io/gh/straw-hat-team/straw_hat_mailer/commit/cf28da1cf520327da01f284c0b6b901506affd9c/build

**Comment by utensil** [comment]
This feature can only be implemented in `codecov/codecov-bash` as codecov-action is merely a thin wrapper for it, and this feature is related to codecov/codecov-bash#199 .

**Comment by ibrahim0814** [comment]
Hi @yordis,

Thank you for bringing this up. Currently, there's no way for us to link back to the build or reference a build number for GitHub Actions because Actions has a limited number of accessible [environment variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables). Whereas Travis has a rich library of [env vars](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) that provide us with a plethora of build information, Actions does not, so therefore, we can't provide this information to you via the card on codecov.io

I'm sorry for the inconvenience, but we'll definitely be on the lookout if GitHub decides to expand its library of env vars to include build info in the future

Ib
