### ISSUE TITLE
Codecov token not found on v4.4.1

### ISSUE THREAD

**Issue by chaizeg** [codecov/codecov-action#1447]
We started seeing failures when running this action since the latest release (v4.4.1), with the following error message : 

```
Error: Codecov token not found. Please provide Codecov token with -t flag.
```

Though the token is clearly set : 
```
Run codecov/codecov-action@v4.4.1
  with:
    ...
    token: *** <-- token is provided
    ...
```

**Comment by amrit110** [comment]
Notice the same issue! #1425

**Comment by pedestrianlove** [comment]
I have the same issue. I workaround this by pinning the version of action to v4.4.0, and everything is working again.

I'm passing codecov_token from the github action secret.

**Comment by marcosschroh** [comment]
Same issue!

**Comment by fmartingr** [comment]
Having the same issue [here](https://github.com/go-shiori/shiori/actions/runs/9355080442/job/25750424983#step:9:1). Codecov is not working for PRs on the same repository, but it's working on PRs from forks.

Tried downgrading the action down to 4.2.0 and the CLI to 0.4.0 without success. Unsure what's the issue here.

**Comment by fmartingr** [comment]
**Update** (using a new comment to notify subscribers) 

Managed to make it work by following this PR changes: https://github.com/napari/napari/pull/6701/files

**Comment by chaizeg** [comment]
We are now hitting a similar issue to https://github.com/codecov/codecov-action/issues/1487 on our PRs after using `v4.5.0` 😕
