### ISSUE TITLE
curl not found 

### ISSUE THREAD

**Issue by AnalogJ** [codecov/codecov-action#152]
I'm seeing the following message when using this action, causing my build to fail. 

```

codecov.sh: line 1694: curl: command not found
==> Uploading to Codecov
codecov.sh: line 1735: curl: command not found
    HTTP 500
Error: Codecov failed with the following error: The process 'bash' failed with exit code 1
```

**Comment by kennethtran93** [comment]
How are you running it?  Check if your build system has curl installed.

**Comment by AnalogJ** [comment]
Doesn’t this action run in its own docker container? Why does my build environment  matter? A curl requirement isn’t listed anywhere in the Readme

**Comment by kennethtran93** [comment]
Just want to confirm if you are using GitHub Actions, and what virtual environment are you using.  Not all environments by default have curl installed.

**Comment by kennethtran93** [comment]
> Doesn’t this action run in its own docker container? Why does my build environment matter? A curl requirement isn’t listed anywhere in the Readme

It's not in the Readme of GitHub Actions because curl is used in the bash uploader script itself.  This GitHub Actions parses some info before passing it along into the bash uploader, which you can see here: (https://github.com/codecov/codecov-bash).  The bash uploader file downloaded by GitHub Actions is done differently through the `requestretry` NodeJS package.
