### ISSUE TITLE
Action with the option "working-directory" fails

### ISSUE THREAD

**Issue by ichizok** [codecov/codecov-action#186]
codecov.sh is written at the initial directory (github.workspace), not at working-directory, thus executing codecov.sh with setting `options.cwd` to working-directory fails.

**Comment by emilydolson** [comment]
Apologies if I'm just doing something wrong, but this seems like it's still an issue. When I set a `working-directory`, the action fails because it is looking for the bash uploader in the working directory (as implemented [here](https://github.com/codecov/codecov-action/blob/75a54f4668ebd491609b92a73a2f3259cd5e631f/src/buildExec.ts#L52)).
