### ISSUE TITLE
Step succeeds even if coverage upload fails

### ISSUE THREAD

**Issue by rowanseymour** [codecov/codecov-action#35]
<img width="632" alt="Captura de Pantalla 2019-11-22 a la(s) 14 51 51" src="https://user-images.githubusercontent.com/675558/69456222-20551d00-0d38-11ea-9416-55dd5956fbcf.png">

**Comment by kyoh86** [comment]
I'm facing the same issue

**Comment by ibrahim0814** [comment]
@rowanseymour This is intentional. We don't want your CI pipeline to break because something went wrong with Codecov. We implement this behavior in our bash uploader and this action is a wrapper around that. You can read more about it in our docs [here](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-uploading-process)

If you'd like to exit with a non-zero code, you can use the `-Z` flag to do so. However, we haven't implemented this functionality in this action, so you'd need to run this shell command instead:

`bash <(curl -s https://codecov.io/bash) -Z`

Perhaps in the future we can add an input for this action if the user wants to specify whether or not the build should fail when Codecov runs into errors :)

**Comment by kyoh86** [comment]
@ibrahim0814 
I see.

But I think that codecov-action is not responsible for executability of following steps.

We can execute following steps even if the codecov-action is failed.
Just setting `failure() || success()` on their `steps.<step>.if`, splitting workflow for them or commenting out the action.

Or rather, it's undesirable that codecov-action fails where no one notices.
Nobody is looking the logs of succeeded steps.
codecov-action is expected to upload coverage to codecov.io. If it is not done, the step should be failure.

**Comment by rowanseymour** [comment]
> We don't want your CI pipeline to break because something went wrong with Codecov

But the reality is that the CI pipeline _has broken_ in this case. If the coverage is not uploaded, then for us, CI has failed, and we need to know about it.

Can it at least be made an option on the codecov-action to fail the step if the upload fails?

**Comment by rowanseymour** [comment]
Today I have a different repo and codecov wasn't finding any coverage files but the step was succeeding. It was a configuration error on my part.. but the step wasn't failing to let me something needed fixed.

**Comment by ibrahim0814** [comment]
Hi all,

We released a new version of this action today (`v1.0.5`) that let's y'all specify an input called `fail_ci_if_error`. You can set this input to `true` if you want any potential errors from the Codecov upload to reflect as a failed step in your CI. This will hopefully ease some worries regarding Codecov failing silently - I'm sorry it took so long on our end to introduce this input for the action

Let me know if it works as anticipated in your pipelines @rowanseymour @kyoh86 and thank you for bringing this issue to our attention in the first place! The major version tag `@v1` should be aligned with this new release

Ib

**Comment by kyoh86** [comment]
@ibrahim0814 it works well. thank you

**Comment by ibrahim0814** [comment]
Awesome! Gonna go ahead and close this issue now
