### ISSUE TITLE
Add documentation on matrix build, only upload coverage once

### ISSUE THREAD

**Issue by jhidding** [codecov/codecov-action#40]
When testing in a matrix, uploads often fail after the first one. I'm testing against different versions of Python, and I only need to upload the coverage information once, by including

```yaml
if: matrix.python-version == 3.8
```

in the codecov job. It took me a while to figure this out, so maybe it is nice to include this in the readme.

**Comment by ibrahim0814** [comment]
Hello @jhidding, thank you for bringing this up!

Regarding your issue about how `uploads often fail after the first one` - could you elaborate more on this? What error do you see on the console? Uploads to Codecov shouldn't fail after the first build in the matrix, but if that's the case, perhaps we need to investigate this issue on our end because other users might be affected by it

**Comment by jhidding** [comment]
Github Actions gives a connection time-out, retries after 30 seconds end-so-on.

**Comment by ibrahim0814** [comment]
@jhidding Any updates on this particular issue? If the problem still persists, we can punch in a support ticket

**Comment by rfgamaral** [comment]
I've started using Codecov with GitHub Actions (on this [test project](https://github.com/rfgamaral/github-actions-playground/actions) for now) and I'm wondering what's the best practice for matrix builds!?

This particular project tests the code against 3 different Node.js version and with my [current workflow](https://github.com/rfgamaral/github-actions-playground/blob/master/.github/workflows/development-ci.yml) I'm uploading 3 different coverage reports (but they are always the same):

![image](https://user-images.githubusercontent.com/96476/73076366-e3331580-3eb5-11ea-9798-cddb9145a14a.png)

This doesn't make much sense to me. Ideally, only one coverage report would be uploaded.

Now, I understand I can add an `if` statement to the upload step like @jhidding mentioned in the original post, but somehow that feels like a hacky solution.

What is the recommended best practice to upload the coverage report only once independently of the number of jobs due to matrix configurations in GitHub actions?

**Comment by zw627** [comment]
## Multiple Node.js and multiple OS

Expand on what @jhidding and @rfgamaral have said. If you are testing on multiple Node.js versions and multiple OS at the same time, something like this will work:

```Yaml
- name: Post Coverage
  uses: codecov/codecov-action@v1.0.10
  if: matrix.os == 'ubuntu-latest' && matrix.node-version == '10.x'
```

This posts the coverage reports to Codecov, only when the OS is `ubuntu-latest` and the Node.js version is `10.x`. Just change `ubuntu-latest` and `10.x` to whatever that suits your needs.

## Result

The `Post Coverage` is skipped when the OS or the Node.js version does not match:

![Annotation 2020-07-05 183237](https://user-images.githubusercontent.com/31707422/86536147-fed32b00-beed-11ea-971b-d55a8b56e966.png)

Two subdirectories `Default` and `Container` have posted their reports once only:

![Annotation 2020-07-05 183211](https://user-images.githubusercontent.com/31707422/86536148-00045800-beee-11ea-9159-0d72ee78a9fb.png)
