### ISSUE TITLE
The `yml` optional input doesn't seem to be working

### ISSUE THREAD

**Issue by rfgamaral** [codecov/codecov-action#51]
If I add the `codecov.yml` file to my project root, everything is working fine:

- https://github.com/rfgamaral/github-actions-playground/commit/88710789c0762827db0c361bc77f999b314cc3c8/checks?check_suite_id=418548260
- https://codecov.io/gh/rfgamaral/github-actions-playground/commit/88710789c0762827db0c361bc77f999b314cc3c8/build

    ![image](https://user-images.githubusercontent.com/96476/73076843-d8c54b80-3eb6-11ea-9d5b-4cc792aa3d15.png)

However, adding the file to `./.github/codecov.yml` and properly configuring my workflow yml file doesn't seem to be working:

- https://github.com/rfgamaral/github-actions-playground/commit/634d90f2d8faa49a53b2e543f40070680991a1f3
- https://github.com/rfgamaral/github-actions-playground/commit/634d90f2d8faa49a53b2e543f40070680991a1f3/checks?check_suite_id=418558348
- https://codecov.io/gh/rfgamaral/github-actions-playground/commit/634d90f2d8faa49a53b2e543f40070680991a1f3/build

    ![image](https://user-images.githubusercontent.com/96476/73077097-643edc80-3eb7-11ea-91a0-d79e171ef1fb.png)

Although the action is saying it found the file, it doesn't seem to be used if you look at codecov.io it will say "No yaml found." and my settings are not being read.

Am I doing something wrong?

**Comment by creekorful** [comment]
I do have the same issue with my repository. https://github.com/creekorful/wks

**Comment by creekorful** [comment]
@ibrahim0814 do you have any idea about what could cause this error?

**Comment by ibrahim0814** [comment]
Hi all,

It seems that specifying the codecov yaml anywhere except for the root of the repo has caused lots of issues for many users. In light of this, I've since removed the `yml` parameter in the [latest release](https://github.com/codecov/codecov-action/releases/tag/v1.0.6) of this action. I'm sorry you guys ran into this issue, but the only fix I can recommend is to put that yaml file at the root of the repository and ignore the `yml` input altogether

Ib
