### ISSUE TITLE
Failed to upload due to ECONNRESET

### ISSUE THREAD

**Issue by sethmlarson** [codecov/codecov-action#71]
https://github.com/urllib3/urllib3/runs/593162103?check_suite_focus=true

**Comment by ivelin** [comment]
Same. Still not resolved.

If we [reference v1](https://github.com/ambianic/ambianic-ui/commit/1e3c53aebe5f9ee6882afe252f78995fc5eb72ad#diff-42c92e55465a3edde413334753e1c2e9), that results in [repetitive failed upload attempts](https://github.com/ambianic/ambianic-ui/pull/364/checks?check_run_id=644612101) and eventually error 400. The github action step does not fail, even though it should because `fail_ci_if_error: true`
This problem is reported already in another issue.

If we reference v1.0.6 we've been [seeing the error reported](https://github.com/ambianic/ambianic-ui/pull/364/checks?check_run_id=644592634) by @sethmlarson .

**Comment by thomasrockhu** [comment]
If this is still an issue @sethmlarson and @ivelin, please open a ticket in our [community boards](https://community.codecov.io).
